services:
  dh.api:
    image: ${DOCKER_REGISTRY-}dhapi
    build:
      context: .
      dockerfile: DH.Api/Dockerfile
    environment:
      MailSettings__Host: live.smtp.mailtrap.io
      MailSettings__DefaultCredentials: "false"
      MailSettings__Port: "587"
      MailSettings__Name: DiceHub
      MailSettings__EmailId: noreply@demomailtrap.co
      MailSettings__UserName: smtp@mailtrap.io
      MailSettings__Password: bc3e40e65ea3d745c48258a9cb565465 
      MailSettings__UseSSL: "true"
    ports:
      - "5000:5000"
      - "5001:5001"

  dicehub.database:
    image: postgres:16
    container_name: dicehub.database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dicehub
    volumes:
      - ./.containers/dicehub-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"